Repository AY2021S2-CS2103T-T10-1/tp, pull requests merged in 2021-03, with the labels that each got.

#128 Create Dog, Breed, DateOfBirth and Sex class
  src/main/java/dog/pawbook/logic/commands/AddCommand.java
  src/main/java/dog/pawbook/logic/commands/AddDogCommand.java
  src/main/java/dog/pawbook/logic/parser/AddDogCommandParser.java
  src/main/java/dog/pawbook/logic/parser/CliSyntax.java
  src/main/java/dog/pawbook/logic/parser/ParserUtil.java
  src/main/java/dog/pawbook/logic/parser/PawbookParser.java
  src/main/java/dog/pawbook/model/managedentity/dog/Breed.java
  src/main/java/dog/pawbook/model/managedentity/dog/DateOfBirth.java
  src/main/java/dog/pawbook/model/managedentity/dog/Dog.java
  src/main/java/dog/pawbook/model/managedentity/dog/Sex.java
Labels: priority.High

#157 Update JsonAdaptedOwner to ensure that the dog IDs are stored
  src/main/java/dog/pawbook/storage/JsonAdaptedOwner.java
Labels: severity.High

#184 Register program into Jackson
  src/main/java/dog/pawbook/storage/JsonAdaptedEntity.java
Labels: severity.High

#202 Edit DG for add/delete feature
  docs/DeveloperGuide.md
  docs/diagrams/DeleteActivityDiagram.puml
  docs/images/AddActivityDiagram.png
  docs/images/DeleteActivityDiagram.png
Labels: priority.Medium

#268 Fix typo that caused null pointers when adding programs
  src/main/java/dog/pawbook/logic/parser/ParserUtil.java
Labels: severity.High, type.Bug

#270 Added basic auto complete feature
  src/main/java/dog/pawbook/ui/AutoCompleteTextField.java
  src/main/java/dog/pawbook/ui/CommandBox.java
  src/main/java/dog/pawbook/ui/CommandSuggestions.java
  src/main/resources/view/CommandBox.fxml
Labels: priority.Medium
